server:
  port: 8090
  servlet:
    context-path: /


spring:
  datasource:
#      username: root
#      password: root
    username: yfb_test
    password: BH_yfb_test1024

#      url: jdbc:mysql://localhost:3307/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useAffectedRows=true&nullCatalogMeansCurrent=true
#      url: jdbc:mysql://localhost:3307/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useAffectedRows=true&nullCatalogMeansCurrent=true
    url: jdbc:mysql://59.111.94.192:3721/ranch_iot_test?useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull

    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.login_demo.entity
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
